feat : 회원 추가 컴포넌트 수정 및 API 연결
TerryEHLee/Danmi pull request #35
Opened 2024-04-13 11:06 UTC by verdantjuly

- http://localhost:4000/users/signup
- POST, Authorization 

- registerSchema.parse 를 이용한 zod 사용
- Form 태그 삭제 -> input에 useState

2024-04-14 22:41 UTC, TerryEHLee requested changes

2024-04-14 22:41 UTC, TerryEHLee commented on src/components/members/adding-member.tsx
> -                "gender",
작성되었는 데이터에 맞추어 백을 변경하는게 좋아보입니다
어짜피 고객 요구에 맞추어 데이터를 변경해야하기 때문입니다

2024-04-14 22:41 UTC, TerryEHLee commented on src/validators/auth.ts
> -  role: z.string().min(2, { message: "역할을 선택하세요." }),
여기도 같은 이유로 남기는게 좋아보여요👍🏻

2024-04-14 22:41 UTC, TerryEHLee commented on src/components/members/adding-member.tsx
> -          <Form {...form}>
폼 태그를 제거하시는 이유가 있으실까요오??

2024-04-15 01:59 UTC, verdantjuly commented on src/components/members/adding-member.tsx
> -          <Form {...form}>
폼태그를 사용하게 되면 특별한 장점 없이 써야 하는 부가적인 태그들이 3개 이상이기 때문에 불필요하다고 생각하였습니다. 또한 폼 태그에 묶어서 보내는 경우 개별 데이터를 useState 로 관리하기 어렵습니다.

2024-04-15 02:03 UTC, verdantjuly commented on src/components/members/adding-member.tsx
> -                "gender",
해당 부분은 사전에 전달받지 못한 경우로 데이터 스키마가 변경되는 경우 데이터베이스 전체를 교체해야 합니다

이 부분은 고객의 요구사항을 은한님께서 종합적으로 가져와 주시면 한번에 수정하는 편이 좋겠습니다

고객의 요구사항이 바뀌어 진행에 차질이 생기는 경우로 API들이 작동되는 것을 테스트해 본 뒤에 변경하여도 될 것 같습니다

2024-04-15 02:04 UTC, verdantjuly commented on src/validators/auth.ts
> -  role: z.string().min(2, { message: "역할을 선택하세요." }),
같은 이유로 추후 변경을 요청드립니다

2024-04-15 03:26 UTC, merged